name: Android CI

on:
  push:
    branches: ["main"]
    tags:
      - "*"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Install zipalign
        run: |
          sudo apt-get update
          sudo apt-get install -y zipalign

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode Keystore
        run: |
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 -d > keystore.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: ./gradlew assembleRelease

      - name: Align APK
        run: |
          cd app/build/outputs/apk/release
          zipalign -v -p 4 app-release-unsigned.apk ludditeinstaller-aligned.apk

      - name: Sign APK
        run: |
          apksigner sign --ks keystore.jks \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            app/build/outputs/apk/release/ludditeinstaller-aligned.apk

      - name: Verify APK
        run: |
          apksigner verify app/build/outputs/apk/release/ludditeinstaller-aligned.apk

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/outputs/apk/release/ludditeinstaller-aligned.apk