name: Android CI

on:
  push:
    branches: ["main"]
    tags:
      - "*"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install build tools
        run: |
          sdkmanager "build-tools;34.0.0"
          echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode Keystore
        run: |
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 -d > $GITHUB_WORKSPACE/keystore.jks
          # Debug: Check if file exists and show workspace
          ls -la $GITHUB_WORKSPACE
          echo "Keystore location: $GITHUB_WORKSPACE/keystore.jks"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: ./gradlew assembleRelease

      - name: Align and Sign APK
        run: |
          cd app/build/outputs/apk/release
          # Debug: Show current directory contents
          pwd
          ls -la
          
          # Align APK
          zipalign -v -p 4 app-release-unsigned.apk ludditeinstaller-aligned.apk
          
          # Debug: Verify aligned APK exists
          ls -la ludditeinstaller-aligned.apk
          
          # Sign APK using absolute paths
          apksigner sign --ks $GITHUB_WORKSPACE/keystore.jks \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            ludditeinstaller-aligned.apk

      - name: Verify APK
        run: |
          cd app/build/outputs/apk/release
          apksigner verify ludditeinstaller-aligned.apk

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/outputs/apk/release/ludditeinstaller-aligned.apk